apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: payments-api
  namespace: argoctopus
  labels:
    app: payments-api
spec:
  replicas: 5
  strategy:
    blueGreen:
      activeService: payments-api
      previewService: payments-api-preview
  # strategy:
  #   canary:
  #     analysis:
  #       templates:
  #         - templateName: payments-api-noop
  #       startingStep: 1
  #     steps:
  #     - analysis:               ← this is a step analysis                                                                                                                                                        
  #       templates:                                     
  #         - templateName: payments-api-noop
  #     - setWeight: 20
  #     - pause: {}
  #     - setWeight: 40
  #     - pause: {duration: 10}
  #     - setWeight: 60
  #     - pause: {duration: 10}
  #     - setWeight: 80
  #     - pause: {duration: 10}
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DB_HOST
              value: "postgres-dev.finpay.internal"
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: argoctopus
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: payments-api
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api-preview
  namespace: argoctopus
spec:
  type: ClusterIP
  ports:
    - port: 81
      targetPort: 81
  selector:
    app: payments-api
---
  apiVersion: argoproj.io/v1alpha1                                                                                                           
  kind: AnalysisTemplate                                                                                                                   
  metadata:
    name: payments-api-noop
    namespace: argoctopus                                                                                                                    
  spec:
    metrics:                                                                                                                                 
      - name: always-pass                                                                                                                  
        interval: 10s
        count: 3
        provider:
          job:
            spec:                                                                                                                            
              backoffLimit: 0
              template:                                                                                                                      
                spec:                                                                                                                      
                  containers:
                    - name: noop
                      image: alpine:3.18
                      command: ["sh", "-c", "exit 0"]                                                                                        
                  restartPolicy: Never